### ISSUE TITLE
NoBrainer with Rails 4.2+Mongoid error

### ISSUE THREAD

**Issue by nengine** [nviennot/nobrainer#140]
Hi, I have Rails 4.2 app running with Mongoid, but when I added NoBrainer gem, it would not start and got errors below.  I'm not so sure something has to do with Rails or NoBrainer.  Any help is greatly appreciated.  Thanks.

```ruby
application.rb
#require 'rails/all'
require 'action_controller/railtie'
require 'action_view/railtie'
require 'action_mailer/railtie'
require 'rails/test_unit/railtie'
require 'sprockets/railtie'
require "active_job/railtie"

document.rb
class Rethink::Document
  include NoBrainer::Document
  field :url
end

```

```
/home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/origin-2.1.1/lib/origin/extensions/symbol.rb:49:in `block in add_key': wrong number of arguments (1 for 0) (ArgumentError)
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/nobrainer-0.23.0/lib/no_brainer/lock.rb:19:in `<class:Lock>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/nobrainer-0.23.0/lib/no_brainer/lock.rb:3:in `<top (required)>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/nobrainer-0.23.0/lib/no_brainer/config.rb:17:in `block in <module:Config>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/nobrainer-0.23.0/lib/no_brainer/config.rb:39:in `call'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/nobrainer-0.23.0/lib/no_brainer/config.rb:39:in `block in apply_defaults'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/nobrainer-0.23.0/lib/no_brainer/config.rb:39:in `each'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/nobrainer-0.23.0/lib/no_brainer/config.rb:39:in `apply_defaults'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/nobrainer-0.23.0/lib/no_brainer/config.rb:57:in `configure'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/nobrainer-0.23.0/lib/no_brainer/railtie.rb:27:in `block in <class:Railtie>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
	from /home/nash/myapp/config/environment.rb:5:in `<top (required)>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/nash/myapp/config.ru:3:in `block in <main>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from /home/nash/myapp/config.ru:in `new'
	from /home/nash/myapp/config.ru:in `<main>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/commands/server.rb:61:in `app'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/commands/server.rb:78:in `start'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/nash/myapp/bin/rails:8:in `require'
	from /home/nash/myapp/bin/rails:8:in `<top (required)>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/spring-1.2.0/lib/spring/client/rails.rb:27:in `load'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/spring-1.2.0/lib/spring/client/rails.rb:27:in `call'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/spring-1.2.0/lib/spring/client/command.rb:7:in `call'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/spring-1.2.0/lib/spring/client.rb:26:in `run'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/spring-1.2.0/bin/spring:48:in `<top (required)>'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/spring-1.2.0/lib/spring/binstub.rb:11:in `load'
	from /home/nash/.rvm/gems/ruby-2.1.3@Rails4.2_myapp/gems/spring-1.2.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/nash/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/nash/myapp/bin/spring:16:in `<top (required)>'
	from /home/nash/myapp/bin/rails:3:in `load'
	from /home/nash/myapp/bin/rails:3:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
```

**Comment by nviennot** [comment]
Mongoid and NoBrainer are not compatible because both ORMs try to add methods on symbols like `:symbol.in`.

I've extracted the symbol decoration functionality in this gem: https://github.com/nviennot/symbol_decoration

If Mongoid was to use this gem, both ORMs would be able to co-exist. I don't have time to make a pull request on the Mongoid project to use symbol_decoration though. Feel free :)

**Comment by nengine** [comment]
Hi, Thanks.  You meant that adding symbol_decoration into Mongoid Gem would work?  I added symbol_decoration into my app but it didn't work.

**Comment by nviennot** [comment]
I mean, changing the Mongoid source code so that it uses `symbol_decoration` to add methods on symbols and not its own thing.

**Comment by nengine** [comment]
Ok. thanks.  I'm not sure how to do this into Mongoid.

**Comment by nviennot** [comment]
First thing is to change https://github.com/mongoid/origin/blob/master/lib/origin/extensions/symbol.rb#L37-L53 to use `symbol_decoration`. And then everywhere it uses its `Key` class to use `Symbol::Decorator`.

**Comment by ffiller** [comment]
Hi @nviennot - Can you advise how to do this today, 2 years later? It doesn't appear to be as simple as replacing `Key.new(self, method, operator, additional, &block)`.

**Comment by nviennot** [comment]
Here you go: https://github.com/nviennot/mongoid/commit/9645529dab8bcbf9148d73fa473a6979c88e9aee

Let me know if you have any questions.

**Comment by ffiller** [comment]
@nviennot Thank you, much appreciated!

**Comment by nengine** [comment]
@ffiller I saw last year in November that rethinkdb was shutting down, and hope that community had picked up from there.
