### ISSUE TITLE
Group by date error

### ISSUE THREAD

**Issue by francocorreasosa** [nviennot/nobrainer#188]
Hi, I tried to query a group by date like this.
```
@users_by_day = NoBrainer.run { |r| r.table('users').group(r.row('created_at').date).count}
```
And I got this error.
```
Started GET "/admin/users/dashboard" for ::1 at 2016-02-07 22:44:13 -0300
Processing by Admin::UserController#dashboard as HTML
Completed 500 Internal Server Error in 5ms

ArgumentError (wrong number of arguments (1 for 0)):
  app/controllers/admin/user_controller.rb:7:in `block in dashboard'
  app/controllers/admin/user_controller.rb:7:in `dashboard'


  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.4ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.8ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (58.6ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.4ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (51.2ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/franco/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (111.8ms)
```

**Comment by nviennot** [comment]
try this: `@users_by_day = NoBrainer.run { |r| r.table('users').group { |u| u['created_at'].date }.count}`

**Comment by francocorreasosa** [comment]
That worked pretty fine, thank you for the quick response.

**Comment by nviennot** [comment]
cool :)
